// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminCreatePet: typeof import('./components/AdminCreatePet.vue')['default']
    AdminMenu: typeof import('./components/AdminMenu.vue')['default']
    CascadingSelect: typeof import('./components/CascadingSelect.vue')['default']
    CreatePet: typeof import('./components/CreatePet.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmptyPetCard: typeof import('./components/EmptyPetCard.vue')['default']
    FilterDialog: typeof import('./components/FilterDialog.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    MapDialog: typeof import('./components/MapDialog.vue')['default']
    MapSelect: typeof import('./components/MapSelect.vue')['default']
    Page: typeof import('./components/Page.vue')['default']
    PetCard: typeof import('./components/PetCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShelterMenu: typeof import('./components/ShelterMenu.vue')['default']
    UploadFile: typeof import('./components/UploadFile.vue')['default']
    VConfirm: typeof import('./components/VConfirm.vue')['default']
    VDialog: typeof import('./components/VDialog.vue')['default']
    VForm: typeof import('./components/VForm.vue')['default']
    VFormItem: typeof import('./components/VFormItem.vue')['default']
    VMessage: typeof import('./components/VMessage.vue')['default']
  }
}
